services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      # Doit correspondre à la fin de ton URL : db_inscription
      POSTGRES_DB: db_inscription
      # Doit correspondre à ton username : postgres
      POSTGRES_USER: postgres
      # Doit correspondre à ton password : mahmoud123#
      POSTGRES_PASSWORD: "mahmoud123#"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: spring_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Ici, on remplace localhost par 'db' (le nom du service plus haut)
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_inscription
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "mahmoud123#"
      # On garde tes réglages Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: